# coding: utf-8

"""
    hawkBit REST APIs

    Eclipse hawkBit™ is a domain-independent back-end framework for rolling out software updates to constrained edge devices as well as more powerful controllers and gateways connected to IP based networking infrastructure.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Link(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'href': 'str',
        'hreflang': 'str',
        'title': 'str',
        'type': 'str',
        'deprecation': 'str',
        'profile': 'str',
        'name': 'str',
        'templated': 'bool'
    }

    attribute_map = {
        'href': 'href',
        'hreflang': 'hreflang',
        'title': 'title',
        'type': 'type',
        'deprecation': 'deprecation',
        'profile': 'profile',
        'name': 'name',
        'templated': 'templated'
    }

    def __init__(self, href=None, hreflang=None, title=None, type=None, deprecation=None, profile=None, name=None, templated=None):  # noqa: E501
        """Link - a model defined in Swagger"""  # noqa: E501
        self._href = None
        self._hreflang = None
        self._title = None
        self._type = None
        self._deprecation = None
        self._profile = None
        self._name = None
        self._templated = None
        self.discriminator = None
        if href is not None:
            self.href = href
        if hreflang is not None:
            self.hreflang = hreflang
        if title is not None:
            self.title = title
        if type is not None:
            self.type = type
        if deprecation is not None:
            self.deprecation = deprecation
        if profile is not None:
            self.profile = profile
        if name is not None:
            self.name = name
        if templated is not None:
            self.templated = templated

    @property
    def href(self):
        """Gets the href of this Link.  # noqa: E501


        :return: The href of this Link.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this Link.


        :param href: The href of this Link.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def hreflang(self):
        """Gets the hreflang of this Link.  # noqa: E501


        :return: The hreflang of this Link.  # noqa: E501
        :rtype: str
        """
        return self._hreflang

    @hreflang.setter
    def hreflang(self, hreflang):
        """Sets the hreflang of this Link.


        :param hreflang: The hreflang of this Link.  # noqa: E501
        :type: str
        """

        self._hreflang = hreflang

    @property
    def title(self):
        """Gets the title of this Link.  # noqa: E501


        :return: The title of this Link.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Link.


        :param title: The title of this Link.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def type(self):
        """Gets the type of this Link.  # noqa: E501


        :return: The type of this Link.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Link.


        :param type: The type of this Link.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def deprecation(self):
        """Gets the deprecation of this Link.  # noqa: E501


        :return: The deprecation of this Link.  # noqa: E501
        :rtype: str
        """
        return self._deprecation

    @deprecation.setter
    def deprecation(self, deprecation):
        """Sets the deprecation of this Link.


        :param deprecation: The deprecation of this Link.  # noqa: E501
        :type: str
        """

        self._deprecation = deprecation

    @property
    def profile(self):
        """Gets the profile of this Link.  # noqa: E501


        :return: The profile of this Link.  # noqa: E501
        :rtype: str
        """
        return self._profile

    @profile.setter
    def profile(self, profile):
        """Sets the profile of this Link.


        :param profile: The profile of this Link.  # noqa: E501
        :type: str
        """

        self._profile = profile

    @property
    def name(self):
        """Gets the name of this Link.  # noqa: E501


        :return: The name of this Link.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Link.


        :param name: The name of this Link.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def templated(self):
        """Gets the templated of this Link.  # noqa: E501


        :return: The templated of this Link.  # noqa: E501
        :rtype: bool
        """
        return self._templated

    @templated.setter
    def templated(self, templated):
        """Sets the templated of this Link.


        :param templated: The templated of this Link.  # noqa: E501
        :type: bool
        """

        self._templated = templated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Link, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Link):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
