# coding: utf-8

"""
    hawkBit REST APIs

    Eclipse hawkBit™ is a domain-independent back-end framework for rolling out software updates to constrained edge devices as well as more powerful controllers and gateways connected to IP based networking infrastructure.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MgmtActionStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'messages': 'list[str]',
        'reported_at': 'int',
        'code': 'int',
        'id': 'int'
    }

    attribute_map = {
        'type': 'type',
        'messages': 'messages',
        'reported_at': 'reportedAt',
        'code': 'code',
        'id': 'id'
    }

    def __init__(self, type=None, messages=None, reported_at=None, code=None, id=None):  # noqa: E501
        """MgmtActionStatus - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._messages = None
        self._reported_at = None
        self._code = None
        self._id = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if messages is not None:
            self.messages = messages
        if reported_at is not None:
            self.reported_at = reported_at
        if code is not None:
            self.code = code
        if id is not None:
            self.id = id

    @property
    def type(self):
        """Gets the type of this MgmtActionStatus.  # noqa: E501


        :return: The type of this MgmtActionStatus.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this MgmtActionStatus.


        :param type: The type of this MgmtActionStatus.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def messages(self):
        """Gets the messages of this MgmtActionStatus.  # noqa: E501


        :return: The messages of this MgmtActionStatus.  # noqa: E501
        :rtype: list[str]
        """
        return self._messages

    @messages.setter
    def messages(self, messages):
        """Sets the messages of this MgmtActionStatus.


        :param messages: The messages of this MgmtActionStatus.  # noqa: E501
        :type: list[str]
        """

        self._messages = messages

    @property
    def reported_at(self):
        """Gets the reported_at of this MgmtActionStatus.  # noqa: E501


        :return: The reported_at of this MgmtActionStatus.  # noqa: E501
        :rtype: int
        """
        return self._reported_at

    @reported_at.setter
    def reported_at(self, reported_at):
        """Sets the reported_at of this MgmtActionStatus.


        :param reported_at: The reported_at of this MgmtActionStatus.  # noqa: E501
        :type: int
        """

        self._reported_at = reported_at

    @property
    def code(self):
        """Gets the code of this MgmtActionStatus.  # noqa: E501


        :return: The code of this MgmtActionStatus.  # noqa: E501
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this MgmtActionStatus.


        :param code: The code of this MgmtActionStatus.  # noqa: E501
        :type: int
        """

        self._code = code

    @property
    def id(self):
        """Gets the id of this MgmtActionStatus.  # noqa: E501


        :return: The id of this MgmtActionStatus.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MgmtActionStatus.


        :param id: The id of this MgmtActionStatus.  # noqa: E501
        :type: int
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MgmtActionStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MgmtActionStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
