# coding: utf-8

"""
    hawkBit REST APIs

    Eclipse hawkBit™ is a domain-independent back-end framework for rolling out software updates to constrained edge devices as well as more powerful controllers and gateways connected to IP based networking infrastructure.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MgmtTargetTypeRequestBodyPost(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'colour': 'str',
        'key': 'str',
        'compatibledistributionsettypes': 'list[MgmtDistributionSetTypeAssignment]'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'colour': 'colour',
        'key': 'key',
        'compatibledistributionsettypes': 'compatibledistributionsettypes'
    }

    def __init__(self, name=None, description=None, colour=None, key=None, compatibledistributionsettypes=None):  # noqa: E501
        """MgmtTargetTypeRequestBodyPost - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._description = None
        self._colour = None
        self._key = None
        self._compatibledistributionsettypes = None
        self.discriminator = None
        self.name = name
        if description is not None:
            self.description = description
        if colour is not None:
            self.colour = colour
        if key is not None:
            self.key = key
        if compatibledistributionsettypes is not None:
            self.compatibledistributionsettypes = compatibledistributionsettypes

    @property
    def name(self):
        """Gets the name of this MgmtTargetTypeRequestBodyPost.  # noqa: E501

        The name of the entity  # noqa: E501

        :return: The name of this MgmtTargetTypeRequestBodyPost.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MgmtTargetTypeRequestBodyPost.

        The name of the entity  # noqa: E501

        :param name: The name of this MgmtTargetTypeRequestBodyPost.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this MgmtTargetTypeRequestBodyPost.  # noqa: E501

        The description of the entity  # noqa: E501

        :return: The description of this MgmtTargetTypeRequestBodyPost.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this MgmtTargetTypeRequestBodyPost.

        The description of the entity  # noqa: E501

        :param description: The description of this MgmtTargetTypeRequestBodyPost.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def colour(self):
        """Gets the colour of this MgmtTargetTypeRequestBodyPost.  # noqa: E501

        The colour of the entity  # noqa: E501

        :return: The colour of this MgmtTargetTypeRequestBodyPost.  # noqa: E501
        :rtype: str
        """
        return self._colour

    @colour.setter
    def colour(self, colour):
        """Sets the colour of this MgmtTargetTypeRequestBodyPost.

        The colour of the entity  # noqa: E501

        :param colour: The colour of this MgmtTargetTypeRequestBodyPost.  # noqa: E501
        :type: str
        """

        self._colour = colour

    @property
    def key(self):
        """Gets the key of this MgmtTargetTypeRequestBodyPost.  # noqa: E501

        Target type key  # noqa: E501

        :return: The key of this MgmtTargetTypeRequestBodyPost.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this MgmtTargetTypeRequestBodyPost.

        Target type key  # noqa: E501

        :param key: The key of this MgmtTargetTypeRequestBodyPost.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def compatibledistributionsettypes(self):
        """Gets the compatibledistributionsettypes of this MgmtTargetTypeRequestBodyPost.  # noqa: E501

        Array of distribution set types that are compatible to that target type  # noqa: E501

        :return: The compatibledistributionsettypes of this MgmtTargetTypeRequestBodyPost.  # noqa: E501
        :rtype: list[MgmtDistributionSetTypeAssignment]
        """
        return self._compatibledistributionsettypes

    @compatibledistributionsettypes.setter
    def compatibledistributionsettypes(self, compatibledistributionsettypes):
        """Sets the compatibledistributionsettypes of this MgmtTargetTypeRequestBodyPost.

        Array of distribution set types that are compatible to that target type  # noqa: E501

        :param compatibledistributionsettypes: The compatibledistributionsettypes of this MgmtTargetTypeRequestBodyPost.  # noqa: E501
        :type: list[MgmtDistributionSetTypeAssignment]
        """

        self._compatibledistributionsettypes = compatibledistributionsettypes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MgmtTargetTypeRequestBodyPost, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MgmtTargetTypeRequestBodyPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
