# coding: utf-8

"""
    hawkBit REST APIs

    Eclipse hawkBit™ is a domain-independent back-end framework for rolling out software updates to constrained edge devices as well as more powerful controllers and gateways connected to IP based networking infrastructure.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.distribution_sets_api import DistributionSetsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDistributionSetsApi(unittest.TestCase):
    """DistributionSetsApi unit test stubs"""

    def setUp(self):
        self.api = DistributionSetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assign_software_modules(self):
        """Test case for assign_software_modules

        Assign a list of software modules to a distribution set  # noqa: E501
        """
        pass

    def test_create_assigned_target(self):
        """Test case for create_assigned_target

        Assigning multiple targets to a single distribution set  # noqa: E501
        """
        pass

    def test_create_distribution_sets(self):
        """Test case for create_distribution_sets

        Creates new Distribution Sets  # noqa: E501
        """
        pass

    def test_create_metadata2(self):
        """Test case for create_metadata2

        Create a list of meta data for a specific distribution set  # noqa: E501
        """
        pass

    def test_delete_assign_software_modules(self):
        """Test case for delete_assign_software_modules

        Delete the assignment of the software module from the distribution set  # noqa: E501
        """
        pass

    def test_delete_distribution_set(self):
        """Test case for delete_distribution_set

        Delete Distribution Set by Id  # noqa: E501
        """
        pass

    def test_delete_metadata2(self):
        """Test case for delete_metadata2

        Delete a single meta data entry from the distribution set  # noqa: E501
        """
        pass

    def test_get_actions_count_by_status_for_distribution_set(self):
        """Test case for get_actions_count_by_status_for_distribution_set

        Return Actions count by status for Distribution Set  # noqa: E501
        """
        pass

    def test_get_assigned_software_modules(self):
        """Test case for get_assigned_software_modules

        Return the assigned software modules of a specific distribution set  # noqa: E501
        """
        pass

    def test_get_assigned_targets1(self):
        """Test case for get_assigned_targets1

        Return assigned targets to a specific distribution set  # noqa: E501
        """
        pass

    def test_get_auto_assign_target_filter_queries(self):
        """Test case for get_auto_assign_target_filter_queries

        Return target filter queries that have the given distribution set as auto assign DS  # noqa: E501
        """
        pass

    def test_get_auto_assignments_count_for_distribution_set(self):
        """Test case for get_auto_assignments_count_for_distribution_set

        Return Auto Assignments count for Distribution Set  # noqa: E501
        """
        pass

    def test_get_distribution_set(self):
        """Test case for get_distribution_set

        Return single Distribution Set  # noqa: E501
        """
        pass

    def test_get_distribution_sets(self):
        """Test case for get_distribution_sets

        Return all Distribution Sets  # noqa: E501
        """
        pass

    def test_get_installed_targets(self):
        """Test case for get_installed_targets

        Return installed targets to a specific distribution set  # noqa: E501
        """
        pass

    def test_get_metadata2(self):
        """Test case for get_metadata2

        Return meta data for Distribution Set  # noqa: E501
        """
        pass

    def test_get_metadata_value2(self):
        """Test case for get_metadata_value2

        Return single meta data value for a specific key of a Distribution Set  # noqa: E501
        """
        pass

    def test_get_rollouts_count_by_status_for_distribution_set(self):
        """Test case for get_rollouts_count_by_status_for_distribution_set

        Return Rollouts count by status for Distribution Set  # noqa: E501
        """
        pass

    def test_get_statistics_for_distribution_set(self):
        """Test case for get_statistics_for_distribution_set

        Return Rollouts, Actions and Auto Assignments counts by Status for Distribution Set  # noqa: E501
        """
        pass

    def test_invalidate_distribution_set(self):
        """Test case for invalidate_distribution_set

        Invalidate a distribution set  # noqa: E501
        """
        pass

    def test_update_distribution_set(self):
        """Test case for update_distribution_set

        Update Distribution Set  # noqa: E501
        """
        pass

    def test_update_metadata2(self):
        """Test case for update_metadata2

        Update single meta data value of a distribution set  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
