# coding: utf-8

"""
    hawkBit REST APIs

    Eclipse hawkBit™ is a domain-independent back-end framework for rolling out software updates to constrained edge devices as well as more powerful controllers and gateways connected to IP based networking infrastructure.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.paged_list_mgmt_action import PagedListMgmtAction  # noqa: E501
from swagger_client.rest import ApiException


class TestPagedListMgmtAction(unittest.TestCase):
    """PagedListMgmtAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagedListMgmtAction(self):
        """Test PagedListMgmtAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.paged_list_mgmt_action.PagedListMgmtAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
