# coding: utf-8

"""
    hawkBit REST APIs

    Eclipse hawkBit™ is a domain-independent back-end framework for rolling out software updates to constrained edge devices as well as more powerful controllers and gateways connected to IP based networking infrastructure.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.software_modules_api import SoftwareModulesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSoftwareModulesApi(unittest.TestCase):
    """SoftwareModulesApi unit test stubs"""

    def setUp(self):
        self.api = SoftwareModulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_metadata1(self):
        """Test case for create_metadata1

        Creates a list of meta data for a specific Software Module  # noqa: E501
        """
        pass

    def test_create_software_modules(self):
        """Test case for create_software_modules

        Create Software Module(s)  # noqa: E501
        """
        pass

    def test_delete_artifact(self):
        """Test case for delete_artifact

        Delete artifact by Id  # noqa: E501
        """
        pass

    def test_delete_metadata1(self):
        """Test case for delete_metadata1

        Delete single meta data entry from the software module  # noqa: E501
        """
        pass

    def test_delete_software_module(self):
        """Test case for delete_software_module

        Delete Software Module by Id  # noqa: E501
        """
        pass

    def test_get_artifact(self):
        """Test case for get_artifact

        Return single Artifact meta data  # noqa: E501
        """
        pass

    def test_get_artifacts(self):
        """Test case for get_artifacts

        Return all meta data of artifacts assigned to a software module  # noqa: E501
        """
        pass

    def test_get_metadata1(self):
        """Test case for get_metadata1

        Return meta data for a Software Module  # noqa: E501
        """
        pass

    def test_get_metadata_value1(self):
        """Test case for get_metadata_value1

        Return single meta data value for a specific key of a Software Module  # noqa: E501
        """
        pass

    def test_get_software_module(self):
        """Test case for get_software_module

        Return Software Module by id  # noqa: E501
        """
        pass

    def test_get_software_modules(self):
        """Test case for get_software_modules

        Return all Software modules  # noqa: E501
        """
        pass

    def test_update_metadata1(self):
        """Test case for update_metadata1

        Update a single meta data value of a Software Module  # noqa: E501
        """
        pass

    def test_update_software_module(self):
        """Test case for update_software_module

        Update Software Module  # noqa: E501
        """
        pass

    def test_upload_artifact(self):
        """Test case for upload_artifact

        Upload artifact  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
