# coding: utf-8

"""
    hawkBit REST APIs

    Eclipse hawkBit™ is a domain-independent back-end framework for rolling out software updates to constrained edge devices as well as more powerful controllers and gateways connected to IP based networking infrastructure.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.mgmt_software_module_assigment import MgmtSoftwareModuleAssigment  # noqa: E501
from swagger_client.rest import ApiException


class TestMgmtSoftwareModuleAssigment(unittest.TestCase):
    """MgmtSoftwareModuleAssigment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMgmtSoftwareModuleAssigment(self):
        """Test MgmtSoftwareModuleAssigment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.mgmt_software_module_assigment.MgmtSoftwareModuleAssigment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
