# coding: utf-8

"""
    hawkBit REST APIs

    Eclipse hawkBit™ is a domain-independent back-end framework for rolling out software updates to constrained edge devices as well as more powerful controllers and gateways connected to IP based networking infrastructure.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.target_types_api import TargetTypesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTargetTypesApi(unittest.TestCase):
    """TargetTypesApi unit test stubs"""

    def setUp(self):
        self.api = TargetTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_compatible_distribution_sets(self):
        """Test case for add_compatible_distribution_sets

        Adding compatibility of a distribution set type to a target type  # noqa: E501
        """
        pass

    def test_create_target_types(self):
        """Test case for create_target_types

        Create target types  # noqa: E501
        """
        pass

    def test_delete_target_type(self):
        """Test case for delete_target_type

        Delete target type by id  # noqa: E501
        """
        pass

    def test_get_compatible_distribution_sets(self):
        """Test case for get_compatible_distribution_sets

        Return list of compatible distribution set types  # noqa: E501
        """
        pass

    def test_get_target_type(self):
        """Test case for get_target_type

        Return target type by id  # noqa: E501
        """
        pass

    def test_get_target_types(self):
        """Test case for get_target_types

        Return all target types  # noqa: E501
        """
        pass

    def test_remove_compatible_distribution_set(self):
        """Test case for remove_compatible_distribution_set

        Remove compatibility of distribution set type from the target type  # noqa: E501
        """
        pass

    def test_update_target_type(self):
        """Test case for update_target_type

        Update target type by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
